name: 'Download Assets'
description: 'Download github.com release assets'

inputs:
  owner:
    required: true
  repo:
    required: true
  tag:
    required: true
  file:
    required: true
  path:
    required: false
  token:
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: download
  color: blue
